//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototype1_1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public client()
        {
            this.dependant = new HashSet<dependant>();
            this.household = new HashSet<household>();
        }
    
        public long ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DoB { get; set; }
        public string Medicare { get; set; }
        public string Gender { get; set; }
        public string Origin { get; set; }
        public string Citizenship { get; set; }
        public string MotherTongue { get; set; }
        public string ServiceLanguage { get; set; }
        public string MaritalStatus { get; set; }
        public string WorkStatus { get; set; }
        public decimal AnnualIncome { get; set; }
        public string Referral { get; set; }
        public string ReasonForServiceUsage { get; set; }
        public string WelfareNumber { get; set; }
    
        public virtual citizenship citizenship1 { get; set; }
        public virtual maritalstatus maritalstatus1 { get; set; }
        public virtual mothertongue mothertongue1 { get; set; }
        public virtual origin origin1 { get; set; }
        public virtual servicelanguage servicelanguage1 { get; set; }
        public virtual workstatus workstatus1 { get; set; }
        public virtual ICollection<dependant> dependant { get; set; }
        public virtual ICollection<household> household { get; set; }
    }
}
