//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototype1_1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class dependant
    {
        public dependant()
        {
            this.client = new HashSet<client>();
        }
    
        public long DependantID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Medicare { get; set; }
        public string Gender { get; set; }
        public string WorkStatus { get; set; }
        public string WelfareNumber { get; set; }
    
        public virtual workstatus workstatus1 { get; set; }
        public virtual ICollection<client> client { get; set; }
    }
}
