//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototype1_1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventtemplate
    {
        public eventtemplate()
        {
            this.slottemplate = new HashSet<slottemplate>();
        }
    
        public long EventID { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> End { get; set; }
        public string EventPeriod { get; set; }
    
        public virtual ICollection<slottemplate> slottemplate { get; set; }
    }
}
