//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototype1_1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class flagtype
    {
        public flagtype()
        {
            this.flag = new HashSet<flag>();
        }
    
        public long FlagID { get; set; }
        public string FlagTitle { get; set; }
        public string FlagPriority { get; set; }
    
        public virtual ICollection<flag> flag { get; set; }
    }
}
