//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototype1_1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class note
    {
        public note()
        {
            this.household = new HashSet<household>();
        }
    
        public long NoteID { get; set; }
        public string NoteInfo { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<household> household { get; set; }
    }
}
