//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototype1_1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class origin
    {
        public origin()
        {
            this.client = new HashSet<client>();
        }
    
        public string OriginName { get; set; }
    
        public virtual ICollection<client> client { get; set; }
    }
}
