//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototype1_1.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class soen390Entities : DbContext
    {
        public soen390Entities()
            : base("name=soen390Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<citizenship> citizenship { get; set; }
        public DbSet<client> client { get; set; }
        public DbSet<dependant> dependant { get; set; }
        public DbSet<@event> @event { get; set; }
        public DbSet<eventtemplate> eventtemplate { get; set; }
        public DbSet<flag> flag { get; set; }
        public DbSet<flagtype> flagtype { get; set; }
        public DbSet<gender> gender { get; set; }
        public DbSet<household> household { get; set; }
        public DbSet<incometype> incometype { get; set; }
        public DbSet<maritalstatus> maritalstatus { get; set; }
        public DbSet<mothertongue> mothertongue { get; set; }
        public DbSet<note> note { get; set; }
        public DbSet<origin> origin { get; set; }
        public DbSet<region> region { get; set; }
        public DbSet<servicelanguage> servicelanguage { get; set; }
        public DbSet<slot> slot { get; set; }
        public DbSet<slottemplate> slottemplate { get; set; }
        public DbSet<workstatus> workstatus { get; set; }
    }
}
