//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototype1_1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class workstatus
    {
        public workstatus()
        {
            this.client = new HashSet<client>();
            this.dependant = new HashSet<dependant>();
        }
    
        public string WorkStatusName { get; set; }
    
        public virtual ICollection<client> client { get; set; }
        public virtual ICollection<dependant> dependant { get; set; }
    }
}
